### ISSUE TITLE
Chromium revision is not downloaded Error

### ISSUE THREAD

**Issue by kargaranamir** [shoniko/abpcrawler_hc#1]
amir@Ferodo:~/Desktop/abpcrawler_hc-master$ npm install
npm WARN abpcrawler_hc@0.0.1 No repository field.
up to date in 1.468s

amir@Ferodo:~/Desktop/abpcrawler_hc-master$ npm start -- -p ./devenv.chrome -u ./top500.domains.csv

> abpcrawler_hc@0.0.1 start /home/amir/Desktop/abpcrawler_hc-master
> node index.js "-p" "./devenv.chrome" "-u" "./top500.domains.csv"

Settings file not found. Proceding with command line arguments.
(node:11396) UnhandledPromiseRejectionWarning: Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at assert (/home/amir/Desktop/abpcrawler_hc-master/node_modules/puppeteer/lib/helper.js:283:11)
    at Function.launch (/home/amir/Desktop/abpcrawler_hc-master/node_modules/puppeteer/lib/Launcher.js:100:7)
(node:11396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11396) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kargaranamir** [comment]
Hi,
How can I handle this error code? 
I don't have any file entitled "devenv.chrome" in my repo .
Thanks

**Comment by kargaranamir** [comment]
This error caused because occurred during installing puppeteer@1.7.0  : 

npm WARN abpcrawler_hc@0.0.1 No repository field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.7.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by kargaranamir** [comment]
and in more details : 

ERROR: Failed to download Chromium r579032! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: Download failed: server returned code 403. URL: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/579032/chrome-linux.zip
    at response (/home/amir/Downloads/abpcrawler_hc-master/node_modules/puppeteer/lib/BrowserFetcher.js:207:21)

**Comment by shoniko** [comment]
Is URL https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/579032/chrome-linux.zip reachable from a regular browser for you?

**Comment by kargaranamir** [comment]
Thanks for your response, No because of sanctions I don't have access.
also, I couldn't use VPN for it and when I use VPN  running code sticks, but I can separately download this zip file.
is there any way to merge both of them?
